# fly.toml app configuration file for projet-final-studi-nameless-shadow-8443

app = "projet-final-studi-nameless-shadow-8443"
primary_region = "cdg"

[http_service]
  internal_port = 8000          # Gunicorn écoute sur 8000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  # Health check pour Fly (tableau)
  checks = [
    { type = "http", path = "/", interval = 10000, timeout = 2000, grace_period = 5000, method = "GET" }
  ]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1