# Generated by Django 5.0.4 on 2026-06-16 16:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('tous_risques', 'Assurance tous risques'), ('depannage', 'Assistance depannage'), ('maintenance', 'Entretien & SAV'), ('controle_technique', 'Contrôle technique')], max_length=30, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Prix mensuel (€)')),
                ('is_included', models.BooleanField(default=False, help_text="Si cochée, l'option est offerte sans supplément.", verbose_name="Incluse dans l'abonnement")),
            ],
            options={
                'verbose_name': 'Option de location',
                'verbose_name_plural': 'Options de location',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('motorisation', models.CharField(blank=True, max_length=50, verbose_name='Motorisation')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('kilometrage', models.PositiveIntegerField(verbose_name='Kilométrage')),
                ('numero_vin', models.CharField(max_length=17, unique=True, verbose_name='N° VIN')),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix de vente')),
                ('loyer_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Loyer mensuel')),
                ('mode', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], default='vente', max_length=20, verbose_name='Mode')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loue'), ('vendu', 'Vendu'), ('indisponible', 'Indisponible')], default='disponible', max_length=15, verbose_name='Statut')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/', verbose_name='Photo principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicule',
                'verbose_name_plural': 'Vehicules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_type', models.CharField(choices=[('achat', 'Achat'), ('location', 'Location longue durée')], max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('en_cours', "En cours d'examen"), ('approuve', 'Approuvé'), ('rejete', 'Refusé'), ('annule', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('location_duration_months', models.PositiveSmallIntegerField(blank=True, help_text='Applicable uniquement pour une location LLD.', null=True, verbose_name='Durée (mois)')),
                ('client_notes', models.TextField(blank=True, verbose_name='Notes du client')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Décidé le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('location_options', models.ManyToManyField(blank=True, to='myapp.optionlocation', verbose_name='Options choisies')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='myapp.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identite', "Pièce d'identité"), ('preuve_revenu', 'Justificatif de revenus'), ('preuve_residence', 'Justificatif de domicile'), ('permis_conduire', 'Permis de conduire'), ('releve_bancaire', 'Relevé bancaire'), ('autre', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('file', models.FileField(upload_to='dossiers/documents/', verbose_name='Fichier')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Nom du fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.dossier')),
            ],
            options={
                'verbose_name': 'Document du dossier',
                'verbose_name_plural': 'Documents du dossier',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(blank=True, max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.dossier')),
            ],
            options={
                'verbose_name': 'Historique dossier',
                'verbose_name_plural': 'Historiques dossiers',
                'ordering': ['-changed_at'],
            },
        ),
    ]
