# Generated by Django 5.0.4 on 2025-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_offres_id_alter_roles_id_alter_tickets_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
