# Generated by Django 5.0.4 on 2025-04-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_roles_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_offres_user', to='myapp.offres'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_tickets_user', to='myapp.users'),
        ),
    ]
