# Generated by Django 5.0.4 on 2025-10-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='lieu',
            field=models.CharField(default='À définir', help_text="Lieu de l'épreuve", max_length=255),
        ),
    ]
