# Generated by Django 5.0.4 on 2025-04-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_tickets_offre_alter_tickets_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
