# Generated by Django 5.0.4 on 2026-06-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_dossierdocument_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionlocation',
            options={},
        ),
        migrations.RemoveField(
            model_name='optionlocation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='optionlocation',
            name='is_included',
        ),
        migrations.RemoveField(
            model_name='optionlocation',
            name='label',
        ),
        migrations.RemoveField(
            model_name='optionlocation',
            name='prix_mensuel',
        ),
        migrations.AlterField(
            model_name='optionlocation',
            name='code',
            field=models.CharField(choices=[('tous_risques', 'Assurance tous risques'), ('depannage', 'Assistance dépannage'), ('maintenance', 'Entretien & SAV'), ('controle_technique', 'Contrôle technique')], max_length=30, unique=True),
        ),
    ]
