# Generated by Django 5.0.4 on 2026-06-20 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_optionlocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='location_options',
        ),
        migrations.AlterModelOptions(
            name='dossier',
            options={},
        ),
        migrations.AlterField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='client_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='dossier_type',
            field=models.CharField(choices=[('achat', 'Achat'), ('location', 'Location longue durée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='location_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dossiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('approuve', 'Approuvé'), ('rejete', 'Refusé')], default='soumis', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='myapp.vehicule'),
        ),
        migrations.DeleteModel(
            name='OptionLocation',
        ),
        migrations.AddField(
            model_name='dossier',
            name='location_options',
            field=models.JSONField(blank=True, help_text="Liste des codes d'options sélectionnées", null=True),
        ),
    ]
