# Generated by Django 5.0.4 on 2025-10-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('discipline', models.CharField(help_text="Nom du sport, par exemple 'Athletisme', 'Natation' etc..", max_length=100)),
                ('genre', models.CharField(help_text='Homme / Femme', max_length=10)),
                ('competition', models.CharField(help_text="Nom de l'épreuve, par exemple 'Finale - 100 mètres", max_length=50)),
                ('tarif', models.DecimalField(decimal_places=2, help_text='Tarif en euros', max_digits=6)),
            ],
        ),
    ]
