# Generated by Django 5.0.4 on 2026-06-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_optionlocation_vehicule_dossier_dossierdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='myapp.vehicule', verbose_name='Véhicule'),
        ),
    ]
