# Generated by Django 5.0.4 on 2025-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_epreuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
    ]
