# Generated by Django 5.0.4 on 2026-06-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dossier_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('approuve', 'Approuvé'), ('rejete', 'Refusé')], default='soumis', max_length=20, verbose_name='Statut'),
        ),
    ]
