# Generated by Django 5.0.4 on 2026-06-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_dossier_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=15, verbose_name='Statut'),
        ),
    ]
