# Generated by Django 5.0.4 on 2025-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_epreuve_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='temp', editable=False, max_length=64, unique=True),
        ),
    ]
