# Generated by Django 5.0.4 on 2026-06-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierdocument',
            name='document_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dossierdocument',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dossierdocument',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
