# Generated by Django 5.0.4 on 2026-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_dossierdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierdocument',
            name='document_type',
            field=models.CharField(choices=[('identite', "Pièce d'identité"), ('preuve_revenu', 'Justificatif de revenus'), ('preuve_residence', 'Justificatif de domicile'), ('permis_conduire', 'Permis de conduire'), ('releve_bancaire', 'Relevé bancaire'), ('autre', 'Autre')], max_length=50),
        ),
    ]
