# Generated by Django 5.0.4 on 2026-06-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_dossier_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='location_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='location_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
