# Generated by Django 5.0.4 on 2026-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_dossier_location_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='location_options',
        ),
        migrations.AddField(
            model_name='dossier',
            name='location_options',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='myapp.optionlocation'),
        ),
    ]
