# Generated by Django 5.0.4 on 2026-06-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ticket_qr_code'),
        ('myapp', '0012_optionlocation_remove_dossier_location_options_and_more'),
    ]

    operations = [
    ]
